"""empty message

Revision ID: 04bc3a7b10b2
Revises: dfc39418cd95
Create Date: 2026-02-25 15:40:54.573256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04bc3a7b10b2'
down_revision: Union[str, Sequence[str], None] = 'dfc39418cd95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('camara_deputados_historico', sa.Column('hash', sa.CHAR(length=32), nullable=False))
    op.create_unique_constraint(op.f('uq_camara_deputados_historico_hash'), 'camara_deputados_historico', ['hash'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_camara_deputados_historico_hash'), 'camara_deputados_historico', type_='unique')
    op.drop_column('camara_deputados_historico', 'hash')
    # ### end Alembic commands ###
