"""retirado limite string tasks_ignoradas lote

Revision ID: 0ef70166dc96
Revises: ca1b8cfe7542
Create Date: 2026-02-19 13:54:56.491814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ef70166dc96'
down_revision: Union[str, Sequence[str], None] = 'ca1b8cfe7542'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lote', 'mensagem',
               existing_type=sa.VARCHAR(length=3000),
               type_=sa.String(length=256),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lote', 'mensagem',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=3000),
               existing_nullable=True)
    # ### end Alembic commands ###
