"""empty message

Revision ID: 111a030bffe6
Revises: 4ce0a67160dc
Create Date: 2026-03-09 16:53:27.494770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '111a030bffe6'
down_revision: Union[str, Sequence[str], None] = '4ce0a67160dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('camara_orgaos_detalhes',
    sa.Column('id_orgao', sa.Integer(), nullable=False),
    sa.Column('data_inicio', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_instalacao', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data_fim', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data_fim_original', sa.DateTime(timezone=True), nullable=True),
    sa.Column('url_website', sa.Text(), nullable=True),
    sa.Column('id_lote', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, cycle=False), nullable=False),
    sa.ForeignKeyConstraint(['id_lote'], ['lote.id'], name=op.f('fk_camara_orgaos_detalhes_id_lote')),
    sa.ForeignKeyConstraint(['id_orgao'], ['camara_orgaos.id_orgao'], name=op.f('fk_camara_orgaos_detalhes_id_orgao')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_camara_orgaos_detalhes')),
    sa.UniqueConstraint('id_orgao', name=op.f('uq_camara_orgaos_detalhes_id_orgao'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('camara_orgaos_detalhes')
    # ### end Alembic commands ###
