"""empty message

Revision ID: 286ef96d3964
Revises: e91f1736650e
Create Date: 2026-03-13 11:36:01.466928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '286ef96d3964'
down_revision: Union[str, Sequence[str], None] = 'e91f1736650e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('camara_orgaos', 'data_inicio',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.create_foreign_key(op.f('fk_camara_partidos_id_lider'), 'camara_partidos', 'camara_deputados', ['id_lider'], ['id_deputado'], use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_camara_partidos_id_lider'), 'camara_partidos', type_='foreignkey')
    op.alter_column('camara_orgaos', 'data_inicio',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    # ### end Alembic commands ###
