"""add camara_deputados_profissoes

Revision ID: 2f1f2dbd6f7a
Revises: 94bfc1a0da9c
Create Date: 2026-02-26 12:22:55.368092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f1f2dbd6f7a'
down_revision: Union[str, Sequence[str], None] = '94bfc1a0da9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('camara_deputados_profissoes',
    sa.Column('id_deputado', sa.Integer(), nullable=False),
    sa.Column('data_hora', sa.DateTime(timezone=True), nullable=False),
    sa.Column('titulo', sa.Text(), nullable=False),
    sa.Column('id_lote', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, cycle=False), nullable=False),
    sa.ForeignKeyConstraint(['id_deputado'], ['camara_deputados.id_deputado'], name=op.f('fk_camara_deputados_profissoes_id_deputado')),
    sa.ForeignKeyConstraint(['id_lote'], ['lote.id'], name=op.f('fk_camara_deputados_profissoes_id_lote')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_camara_deputados_profissoes')),
    sa.UniqueConstraint('titulo', name=op.f('uq_camara_deputados_profissoes_titulo'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('camara_deputados_profissoes')
    # ### end Alembic commands ###
