"""fix lote mixin em camara_legislatura

Revision ID: 37260a80e0c1
Revises: 5d41f6a84cda
Create Date: 2026-02-24 16:20:13.055524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37260a80e0c1'
down_revision: Union[str, Sequence[str], None] = '5d41f6a84cda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('camara_legislatura', sa.Column('id_lote', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'camara_legislatura', 'lote', ['id_lote'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'camara_legislatura', type_='foreignkey')
    op.drop_column('camara_legislatura', 'id_lote')
    # ### end Alembic commands ###
