"""fix nome camara_tipos_orgaos

Revision ID: 375d83eb4673
Revises: 6118c50afa64
Create Date: 2026-03-07 16:37:03.477222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '375d83eb4673'
down_revision: Union[str, Sequence[str], None] = '6118c50afa64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('camara_tipos_orgaos',
    sa.Column('codigo', sa.Integer(), nullable=False),
    sa.Column('nome', sa.Text(), nullable=False),
    sa.Column('id_lote', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, cycle=False), nullable=False),
    sa.ForeignKeyConstraint(['id_lote'], ['lote.id'], name=op.f('fk_camara_tipos_orgaos_id_lote')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_camara_tipos_orgaos')),
    sa.UniqueConstraint('codigo', name=op.f('uq_camara_tipos_orgaos_codigo')),
    sa.UniqueConstraint('nome', name=op.f('uq_camara_tipos_orgaos_nome'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('camara_tipos_orgaos')
    # ### end Alembic commands ###
