"""log_linhas add total

Revision ID: 3a4dc039a101
Revises: a62b3ef1774b
Create Date: 2026-02-27 13:11:03.110093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a4dc039a101'
down_revision: Union[str, Sequence[str], None] = 'a62b3ef1774b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('log_linhas', sa.Column('total', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('log_linhas', 'total')
    # ### end Alembic commands ###
