"""tab log_run_ids excluida

Revision ID: 4834a9a2d388
Revises: 68a9e0dd90b9
Create Date: 2026-02-20 19:49:42.397571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4834a9a2d388'
down_revision: Union[str, Sequence[str], None] = '68a9e0dd90b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('flow_run_ids')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flow_run_ids',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('lote_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('pipeline_flow_run_id', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('tse_flow_run_id', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('camara_flow_run_id', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('senado_flow_run_id', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['lote_id'], ['lote.id'], name=op.f('flow_run_ids_lote_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('flow_run_ids_pkey')),
    sa.UniqueConstraint('camara_flow_run_id', name=op.f('flow_run_ids_camara_flow_run_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('lote_id', name=op.f('flow_run_ids_lote_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('pipeline_flow_run_id', name=op.f('flow_run_ids_pipeline_flow_run_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('senado_flow_run_id', name=op.f('flow_run_ids_senado_flow_run_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('tse_flow_run_id', name=op.f('flow_run_ids_tse_flow_run_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
