"""tabs flow_run_ids e logs

Revision ID: 4ac899f18997
Revises: 4e3225b69876
Create Date: 2026-02-20 17:14:29.363569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ac899f18997'
down_revision: Union[str, Sequence[str], None] = '4e3225b69876'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flow_run_ids',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, cycle=False), nullable=False),
    sa.Column('lote_id', sa.Integer(), nullable=False),
    sa.Column('pipeline_flow_run_id', sa.String(length=256), nullable=False),
    sa.Column('tse_flow_run_id', sa.String(length=256), nullable=False),
    sa.Column('camara_flow_run_id', sa.String(length=256), nullable=False),
    sa.Column('senado_flow_run_id', sa.String(length=256), nullable=False),
    sa.ForeignKeyConstraint(['lote_id'], ['lote.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('camara_flow_run_id'),
    sa.UniqueConstraint('lote_id'),
    sa.UniqueConstraint('pipeline_flow_run_id'),
    sa.UniqueConstraint('senado_flow_run_id'),
    sa.UniqueConstraint('tse_flow_run_id')
    )
    op.create_table('logs',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, cycle=False), nullable=False),
    sa.Column('lote_id', sa.Integer(), nullable=False),
    sa.Column('data_hora', sa.DateTime(timezone=True), nullable=True),
    sa.Column('level', sa.String(length=24), nullable=False),
    sa.Column('flow_run', sa.String(length=256), nullable=False),
    sa.Column('mensagem', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['lote_id'], ['lote.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lote_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('logs')
    op.drop_table('flow_run_ids')
    # ### end Alembic commands ###
