"""fix uq constraint camara_tipos_orgaos

Revision ID: 4fdc331b829f
Revises: 375d83eb4673
Create Date: 2026-03-07 16:47:41.063221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fdc331b829f'
down_revision: Union[str, Sequence[str], None] = '375d83eb4673'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_camara_tipos_orgaos_nome'), 'camara_tipos_orgaos', type_='unique')
    op.create_unique_constraint('uq_tipos_orgaos', 'camara_tipos_orgaos', ['codigo', 'nome'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_tipos_orgaos', 'camara_tipos_orgaos', type_='unique')
    op.create_unique_constraint(op.f('uq_camara_tipos_orgaos_nome'), 'camara_tipos_orgaos', ['nome'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
