"""col mensagem tab lote

Revision ID: 4fe47af25a86
Revises: b0bae8cf553f
Create Date: 2026-02-19 12:44:26.661185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fe47af25a86'
down_revision: Union[str, Sequence[str], None] = 'b0bae8cf553f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lote', sa.Column('mensagem', sa.String(length=256), nullable=True))
    op.alter_column('lote', 'tasks_ignoradas',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=256),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lote', 'tasks_ignoradas',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
    op.drop_column('lote', 'mensagem')
    # ### end Alembic commands ###
