"""add col use_files tab lote

Revision ID: 553df6022c29
Revises: 3a4dc039a101
Create Date: 2026-03-03 12:07:56.814838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '553df6022c29'
down_revision: Union[str, Sequence[str], None] = '3a4dc039a101'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lote', sa.Column('use_files', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lote', 'use_files')
    # ### end Alembic commands ###
