"""remove unique nome in camara_orgaos

Revision ID: 5fd49254edd5
Revises: 631e8916077b
Create Date: 2026-03-09 12:14:30.212321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fd49254edd5'
down_revision: Union[str, Sequence[str], None] = '631e8916077b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_camara_orgaos_nome'), 'camara_orgaos', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_camara_orgaos_nome'), 'camara_orgaos', ['nome'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
