"""fix nome_publicacao camara_orgaos

Revision ID: 631e8916077b
Revises: a542de2fd369
Create Date: 2026-03-09 11:58:59.743429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '631e8916077b'
down_revision: Union[str, Sequence[str], None] = 'a542de2fd369'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('camara_orgaos', 'nome_publicacao',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('camara_orgaos', 'nome_publicacao',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
