"""empty message

Revision ID: 64e0ed4d7b10
Revises: 
Create Date: 2026-03-11 11:30:00.407978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64e0ed4d7b10'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lote',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, cycle=False), nullable=False),
    sa.Column('todos_flows_ok', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('data_inicio_lote', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('data_fim_lote', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('data_inicio_extract', sa.Date(), nullable=False),
    sa.Column('data_fim_extract', sa.Date(), nullable=False),
    sa.Column('flows_ignoradas', sa.String(length=25), nullable=True),
    sa.Column('tasks_ignoradas', sa.Text(), nullable=True),
    sa.Column('resetar_cache', sa.Boolean(), nullable=False),
    sa.Column('mensagem', sa.Text(), nullable=True),
    sa.Column('urls_nao_baixadas', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('use_files', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lote'))
    )
    op.create_table('erros_extract',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, cycle=False), nullable=False),
    sa.Column('lote_id', sa.Integer(), nullable=False),
    sa.Column('task', sa.String(length=50), nullable=False),
    sa.Column('data_hora', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('mensagem', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('baixado', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('data_hora_baixado', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lote_baixado', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lote_id'], ['lote.id'], name=op.f('fk_erros_extract_lote_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_erros_extract')),
    sa.UniqueConstraint('url', name=op.f('uq_erros_extract_url'))
    )
    op.create_table('log_linhas',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, cycle=False), nullable=False),
    sa.Column('id_lote', sa.Integer(), nullable=False),
    sa.Column('tabela', sa.Text(), nullable=False),
    sa.Column('inseridos', sa.Integer(), nullable=False),
    sa.Column('atualizados', sa.Integer(), nullable=False),
    sa.Column('ignorados', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_lote'], ['lote.id'], name=op.f('fk_log_linhas_id_lote')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_log_linhas'))
    )
    op.create_table('logs',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, cycle=False), nullable=False),
    sa.Column('lote_id', sa.Integer(), nullable=False),
    sa.Column('data_hora', sa.DateTime(timezone=True), nullable=True),
    sa.Column('level', sa.String(length=24), nullable=False),
    sa.Column('flow_run_name', sa.String(length=256), nullable=False),
    sa.Column('task_run_name', sa.String(length=256), nullable=True),
    sa.Column('mensagem', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['lote_id'], ['lote.id'], name=op.f('fk_logs_lote_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_logs'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('logs')
    op.drop_table('log_linhas')
    op.drop_table('erros_extract')
    op.drop_table('lote')
    # ### end Alembic commands ###
