"""fix legislatura unique partidos

Revision ID: 683f443a6692
Revises: 41498b641a45
Create Date: 2026-02-24 23:58:03.201444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '683f443a6692'
down_revision: Union[str, Sequence[str], None] = '41498b641a45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_camara_partidos_id_legislatura'), 'camara_partidos', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_camara_partidos_id_legislatura'), 'camara_partidos', ['id_legislatura'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
