"""flow_runs_ids nullable id flows

Revision ID: 68a9e0dd90b9
Revises: 4ac899f18997
Create Date: 2026-02-20 17:16:35.438948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68a9e0dd90b9'
down_revision: Union[str, Sequence[str], None] = '4ac899f18997'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('flow_run_ids', 'tse_flow_run_id',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    op.alter_column('flow_run_ids', 'camara_flow_run_id',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    op.alter_column('flow_run_ids', 'senado_flow_run_id',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('flow_run_ids', 'senado_flow_run_id',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
    op.alter_column('flow_run_ids', 'camara_flow_run_id',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
    op.alter_column('flow_run_ids', 'tse_flow_run_id',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
    # ### end Alembic commands ###
