"""empty message

Revision ID: 6e5ef163685e
Revises: 861d7925dac4
Create Date: 2026-03-10 12:58:59.722009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e5ef163685e'
down_revision: Union[str, Sequence[str], None] = '861d7925dac4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('camara_orgaos_membros', sa.Column('id_legislatura', sa.Integer(), nullable=False))
    op.create_foreign_key(op.f('fk_camara_orgaos_membros_id_legislatura'), 'camara_orgaos_membros', 'camara_legislatura', ['id_legislatura'], ['id_legislatura'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_camara_orgaos_membros_id_legislatura'), 'camara_orgaos_membros', type_='foreignkey')
    op.drop_column('camara_orgaos_membros', 'id_legislatura')
    # ### end Alembic commands ###
