"""empty message

Revision ID: 701fec2f71a0
Revises: 683f443a6692
Create Date: 2026-02-25 00:14:29.335727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '701fec2f71a0'
down_revision: Union[str, Sequence[str], None] = '683f443a6692'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('camara_deputados', sa.Column('id_partido', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_camara_deputados_id_partido'), 'camara_deputados', 'camara_partidos', ['id_partido'], ['id_partido'])
    op.drop_column('camara_deputados', 'sigla_partido')
    op.drop_constraint(op.f('fk_camara_deputados_redes_sociais_id_deputado'), 'camara_deputados_redes_sociais', type_='foreignkey')
    op.create_foreign_key(op.f('fk_camara_deputados_redes_sociais_id_deputado'), 'camara_deputados_redes_sociais', 'camara_deputados', ['id_deputado'], ['id_deputado'])
    op.drop_constraint(op.f('fk_camara_partidos_id_lider'), 'camara_partidos', type_='foreignkey')
    op.create_foreign_key(op.f('fk_camara_partidos_id_lider'), 'camara_partidos', 'camara_deputados', ['id_lider'], ['id_deputado'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_camara_partidos_id_lider'), 'camara_partidos', type_='foreignkey')
    op.create_foreign_key(op.f('fk_camara_partidos_id_lider'), 'camara_partidos', 'camara_deputados', ['id_lider'], ['id'])
    op.drop_constraint(op.f('fk_camara_deputados_redes_sociais_id_deputado'), 'camara_deputados_redes_sociais', type_='foreignkey')
    op.create_foreign_key(op.f('fk_camara_deputados_redes_sociais_id_deputado'), 'camara_deputados_redes_sociais', 'camara_deputados', ['id_deputado'], ['id'])
    op.add_column('camara_deputados', sa.Column('sigla_partido', sa.VARCHAR(length=15), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('fk_camara_deputados_id_partido'), 'camara_deputados', type_='foreignkey')
    op.drop_column('camara_deputados', 'id_partido')
    # ### end Alembic commands ###
