"""legislaturas lideres e mesa

Revision ID: 74d3c3cd6d19
Revises: 553df6022c29
Create Date: 2026-03-05 15:30:17.201653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74d3c3cd6d19'
down_revision: Union[str, Sequence[str], None] = '553df6022c29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('camara_legislaturas_lideres',
    sa.Column('id_deputado', sa.Integer(), nullable=False),
    sa.Column('id_legislatura', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.Text(), nullable=False),
    sa.Column('bancada_tipo', sa.Text(), nullable=False),
    sa.Column('bancada_nome', sa.Text(), nullable=False),
    sa.Column('id_bancada', sa.Integer(), nullable=True),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=True),
    sa.Column('id_lote', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, cycle=False), nullable=False),
    sa.ForeignKeyConstraint(['id_deputado'], ['camara_deputados.id_deputado'], name=op.f('fk_camara_legislaturas_lideres_id_deputado')),
    sa.ForeignKeyConstraint(['id_lote'], ['lote.id'], name=op.f('fk_camara_legislaturas_lideres_id_lote')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_camara_legislaturas_lideres'))
    )
    op.create_table('camara_legislaturas_mesa',
    sa.Column('id_deputado', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.Text(), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=True),
    sa.Column('id_lote', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, cycle=False), nullable=False),
    sa.ForeignKeyConstraint(['id_deputado'], ['camara_deputados.id_deputado'], name=op.f('fk_camara_legislaturas_mesa_id_deputado')),
    sa.ForeignKeyConstraint(['id_lote'], ['lote.id'], name=op.f('fk_camara_legislaturas_mesa_id_lote')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_camara_legislaturas_mesa'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('camara_legislaturas_mesa')
    op.drop_table('camara_legislaturas_lideres')
    # ### end Alembic commands ###
