"""fix constraint camara_deputados_profissoes

Revision ID: 79a5765954f8
Revises: a005b6397dce
Create Date: 2026-02-26 12:47:26.814417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79a5765954f8'
down_revision: Union[str, Sequence[str], None] = 'a005b6397dce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_camara_deputados_profissoes_titulo'), 'camara_deputados_profissoes', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_camara_deputados_profissoes_titulo'), 'camara_deputados_profissoes', ['titulo'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
