"""initial version

Revision ID: 82e661dcbd6c
Revises: 
Create Date: 2026-03-09 11:31:27.746995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82e661dcbd6c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('camara_tipos_orgaos',
    sa.Column('id_tipo_orgao', sa.Integer(), nullable=False),
    sa.Column('nome', sa.Text(), nullable=False),
    sa.Column('id_lote', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, cycle=False), nullable=False),
    sa.ForeignKeyConstraint(['id_lote'], ['lote.id'], name=op.f('fk_camara_tipos_orgaos_id_lote')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_camara_tipos_orgaos')),
    sa.UniqueConstraint('id_tipo_orgao', 'nome', name='uq_tipos_orgaos'),
    sa.UniqueConstraint('id_tipo_orgao', name=op.f('uq_camara_tipos_orgaos_id_tipo_orgao'))
    )
    op.create_table('camara_orgaos',
    sa.Column('id_orgao', sa.Integer(), nullable=False),
    sa.Column('sigla', sa.Text(), nullable=False),
    sa.Column('nome', sa.Text(), nullable=False),
    sa.Column('apelido', sa.Text(), nullable=False),
    sa.Column('id_tipo_orgao', sa.Integer(), nullable=False),
    sa.Column('nome_publicacao', sa.Text(), nullable=False),
    sa.Column('nome_resumido', sa.Text(), nullable=False),
    sa.Column('id_lote', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, cycle=False), nullable=False),
    sa.ForeignKeyConstraint(['id_lote'], ['lote.id'], name=op.f('fk_camara_orgaos_id_lote')),
    sa.ForeignKeyConstraint(['id_tipo_orgao'], ['camara_tipos_orgaos.id_tipo_orgao'], name=op.f('fk_camara_orgaos_id_tipo_orgao')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_camara_orgaos')),
    sa.UniqueConstraint('id_orgao', name=op.f('uq_camara_orgaos_id_orgao')),
    sa.UniqueConstraint('nome', name=op.f('uq_camara_orgaos_nome')),
    sa.UniqueConstraint('sigla', name=op.f('uq_camara_orgaos_sigla'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('camara_orgaos')
    op.drop_table('camara_tipos_orgaos')
    # ### end Alembic commands ###
