"""fix constraint blocos_partidos

Revision ID: 82eafabcbff4
Revises: 7b4121e46228
Create Date: 2026-03-06 15:34:57.008421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82eafabcbff4'
down_revision: Union[str, Sequence[str], None] = '7b4121e46228'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_blocos_partidos'), 'camara_blocos_partidos', type_='unique')
    op.create_unique_constraint(op.f('uq_camara_blocos_partidos_sigla'), 'camara_blocos_partidos', ['sigla'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_camara_blocos_partidos_sigla'), 'camara_blocos_partidos', type_='unique')
    op.create_unique_constraint(op.f('uq_blocos_partidos'), 'camara_blocos_partidos', ['id_bloco', 'sigla'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
