"""empty message

Revision ID: 861d7925dac4
Revises: a2d2a50320fc
Create Date: 2026-03-10 10:40:26.047969

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "861d7925dac4"
down_revision: Union[str, Sequence[str], None] = "a2d2a50320fc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_camara_orgaos_sigla"), "camara_orgaos", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        op.f("uq_camara_orgaos_sigla"),
        "camara_orgaos",
        ["sigla"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
