"""empty message

Revision ID: 8917fd66e3b9
Revises: 111a030bffe6
Create Date: 2026-03-09 18:11:56.349308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8917fd66e3b9'
down_revision: Union[str, Sequence[str], None] = '111a030bffe6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('camara_orgaos_membros',
    sa.Column('id_orgao', sa.Integer(), nullable=False),
    sa.Column('id_deputado', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.Text(), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=True),
    sa.Column('id_lote', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, cycle=False), nullable=False),
    sa.ForeignKeyConstraint(['id_deputado'], ['camara_deputados.id_deputado'], name=op.f('fk_camara_orgaos_membros_id_deputado')),
    sa.ForeignKeyConstraint(['id_lote'], ['lote.id'], name=op.f('fk_camara_orgaos_membros_id_lote')),
    sa.ForeignKeyConstraint(['id_orgao'], ['camara_orgaos.id_orgao'], name=op.f('fk_camara_orgaos_membros_id_orgao')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_camara_orgaos_membros')),
    sa.UniqueConstraint('id_orgao', 'id_deputado', name='uq_orgaos_membros')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('camara_orgaos_membros')
    # ### end Alembic commands ###
