"""Fix camara_deputados_ocupacoes

Revision ID: 94bfc1a0da9c
Revises: 8e85b3b600c9
Create Date: 2026-02-26 11:32:52.197426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94bfc1a0da9c'
down_revision: Union[str, Sequence[str], None] = '8e85b3b600c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('camara_deputados_ocupacoes',
    sa.Column('id_deputado', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.Text(), nullable=False),
    sa.Column('entidade', sa.Text(), nullable=True),
    sa.Column('entidade_uf', sa.CHAR(length=2), nullable=True),
    sa.Column('entidade_pais', sa.Text(), nullable=True),
    sa.Column('ano_inicio', sa.Integer(), nullable=False),
    sa.Column('ano_fim', sa.Integer(), nullable=True),
    sa.Column('id_lote', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, cycle=False), nullable=False),
    sa.ForeignKeyConstraint(['id_deputado'], ['camara_deputados.id_deputado'], name=op.f('fk_camara_deputados_ocupacoes_id_deputado')),
    sa.ForeignKeyConstraint(['id_lote'], ['lote.id'], name=op.f('fk_camara_deputados_ocupacoes_id_lote')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_camara_deputados_ocupacoes')),
    sa.UniqueConstraint('id_deputado', 'titulo', 'ano_inicio', name='uq_deputados_ocupacoes')
    )
    op.create_foreign_key(op.f('fk_camara_partidos_id_lider'), 'camara_partidos', 'camara_deputados', ['id_lider'], ['id_deputado'], use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_camara_partidos_id_lider'), 'camara_partidos', type_='foreignkey')
    op.drop_table('camara_deputados_ocupacoes')
    # ### end Alembic commands ###
