"""add camara_blocos e camara_blocos_partidos

Revision ID: 9a1554185bfb
Revises: de9d848b7bb8
Create Date: 2026-03-06 14:36:01.418637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a1554185bfb'
down_revision: Union[str, Sequence[str], None] = 'de9d848b7bb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('camara_blocos',
    sa.Column('id_bloco', sa.Integer(), nullable=False),
    sa.Column('nome', sa.Text(), nullable=False),
    sa.Column('id_legislatura', sa.Integer(), nullable=False),
    sa.Column('federacao', sa.Boolean(), nullable=False),
    sa.Column('id_lote', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, cycle=False), nullable=False),
    sa.ForeignKeyConstraint(['id_lote'], ['lote.id'], name=op.f('fk_camara_blocos_id_lote')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_camara_blocos')),
    sa.UniqueConstraint('id_bloco', name=op.f('uq_camara_blocos_id_bloco'))
    )
    op.create_table('camara_blocos_partidos',
    sa.Column('id_bloco', sa.Integer(), nullable=False),
    sa.Column('sigla', sa.String(length=15), nullable=False),
    sa.Column('nome', sa.Text(), nullable=False),
    sa.Column('id_lote', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, cycle=False), nullable=False),
    sa.ForeignKeyConstraint(['id_lote'], ['lote.id'], name=op.f('fk_camara_blocos_partidos_id_lote')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_camara_blocos_partidos')),
    sa.UniqueConstraint('nome', name=op.f('uq_camara_blocos_partidos_nome')),
    sa.UniqueConstraint('sigla', name=op.f('uq_camara_blocos_partidos_sigla'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('camara_blocos_partidos')
    op.drop_table('camara_blocos')
    # ### end Alembic commands ###
