"""empty message

Revision ID: 9ac1f4e12bdd
Revises: 701fec2f71a0
Create Date: 2026-02-25 12:51:35.480273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ac1f4e12bdd'
down_revision: Union[str, Sequence[str], None] = '701fec2f71a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('camara_deputados_redes_sociais', sa.Column('url', sa.Text(), nullable=False))
    op.create_unique_constraint(op.f('uq_camara_deputados_redes_sociais_url'), 'camara_deputados_redes_sociais', ['url'])
    op.drop_column('camara_deputados_redes_sociais', 'rede_social')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('camara_deputados_redes_sociais', sa.Column('rede_social', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('uq_camara_deputados_redes_sociais_url'), 'camara_deputados_redes_sociais', type_='unique')
    op.drop_column('camara_deputados_redes_sociais', 'url')
    # ### end Alembic commands ###
