"""empty message

Revision ID: a2d2a50320fc
Revises: d84f02b834fc
Create Date: 2026-03-09 18:25:30.428120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2d2a50320fc'
down_revision: Union[str, Sequence[str], None] = 'd84f02b834fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_orgaos_membros'), 'camara_orgaos_membros', type_='unique')
    op.create_unique_constraint('uq_orgaos_membros', 'camara_orgaos_membros', ['id_orgao', 'id_deputado', 'titulo', 'data_inicio'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_orgaos_membros', 'camara_orgaos_membros', type_='unique')
    op.create_unique_constraint(op.f('uq_orgaos_membros'), 'camara_orgaos_membros', ['id_orgao', 'id_deputado'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
