"""fix nome_resumido camara_orgaos

Revision ID: a542de2fd369
Revises: 82e661dcbd6c
Create Date: 2026-03-09 11:58:03.489975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a542de2fd369'
down_revision: Union[str, Sequence[str], None] = '82e661dcbd6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('camara_orgaos', 'nome_resumido',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('camara_orgaos', 'nome_resumido',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
