"""add log_linhas

Revision ID: a62b3ef1774b
Revises: 79a5765954f8
Create Date: 2026-02-27 13:08:58.457491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a62b3ef1774b'
down_revision: Union[str, Sequence[str], None] = '79a5765954f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('log_linhas',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, cycle=False), nullable=False),
    sa.Column('id_lote', sa.Integer(), nullable=False),
    sa.Column('tabela', sa.Text(), nullable=False),
    sa.Column('inseridos', sa.Integer(), nullable=False),
    sa.Column('atualizados', sa.Integer(), nullable=False),
    sa.Column('ignorados', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_lote'], ['lote.id'], name=op.f('fk_log_linhas_id_lote')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_log_linhas'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('log_linhas')
    # ### end Alembic commands ###
