"""string 1500 tasks_ignoradas lote

Revision ID: cfb374e35c0a
Revises: 0ef70166dc96
Create Date: 2026-02-19 13:55:52.789676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfb374e35c0a'
down_revision: Union[str, Sequence[str], None] = '0ef70166dc96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lote', 'tasks_ignoradas',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.String(length=1500),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lote', 'tasks_ignoradas',
               existing_type=sa.String(length=1500),
               type_=sa.VARCHAR(length=256),
               existing_nullable=True)
    # ### end Alembic commands ###
