"""fix_uq_constraint camara_deputados_profissoes

Revision ID: d49fb9a07cf4
Revises: 2f1f2dbd6f7a
Create Date: 2026-02-26 12:36:03.959302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd49fb9a07cf4'
down_revision: Union[str, Sequence[str], None] = '2f1f2dbd6f7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_camara_deputados_profissoes_id_deputado'), 'camara_deputados_profissoes', ['id_deputado', 'titulo'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_camara_deputados_profissoes_id_deputado'), 'camara_deputados_profissoes', type_='unique')
    # ### end Alembic commands ###
