"""empty message

Revision ID: da868b948ff5
Revises: 
Create Date: 2026-03-10 16:05:28.965876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da868b948ff5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lote',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, cycle=False), nullable=False),
    sa.Column('todos_flows_ok', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('data_inicio_lote', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('data_fim_lote', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('data_inicio_extract', sa.Date(), nullable=False),
    sa.Column('data_fim_extract', sa.Date(), nullable=False),
    sa.Column('flows_ignoradas', sa.String(length=25), nullable=True),
    sa.Column('tasks_ignoradas', sa.Text(), nullable=True),
    sa.Column('resetar_cache', sa.Boolean(), nullable=False),
    sa.Column('mensagem', sa.Text(), nullable=True),
    sa.Column('urls_nao_baixadas', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('use_files', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lote'))
    )
    op.create_table('camara_blocos_partidos',
    sa.Column('id_bloco', sa.Integer(), nullable=False),
    sa.Column('sigla', sa.String(length=15), nullable=False),
    sa.Column('nome', sa.Text(), nullable=False),
    sa.Column('id_lote', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, cycle=False), nullable=False),
    sa.ForeignKeyConstraint(['id_lote'], ['lote.id'], name=op.f('fk_camara_blocos_partidos_id_lote')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_camara_blocos_partidos')),
    sa.UniqueConstraint('sigla', name=op.f('uq_camara_blocos_partidos_sigla'))
    )
    op.create_table('camara_legislatura',
    sa.Column('id_legislatura', sa.Integer(), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=False),
    sa.Column('id_lote', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, cycle=False), nullable=False),
    sa.ForeignKeyConstraint(['id_lote'], ['lote.id'], name=op.f('fk_camara_legislatura_id_lote')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_camara_legislatura')),
    sa.UniqueConstraint('id_legislatura', name=op.f('uq_camara_legislatura_id_legislatura'))
    )
    op.create_table('camara_orgaos_tipos',
    sa.Column('id_tipo_orgao', sa.Integer(), nullable=False),
    sa.Column('nome', sa.Text(), nullable=False),
    sa.Column('id_lote', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, cycle=False), nullable=False),
    sa.ForeignKeyConstraint(['id_lote'], ['lote.id'], name=op.f('fk_camara_orgaos_tipos_id_lote')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_camara_orgaos_tipos')),
    sa.UniqueConstraint('id_tipo_orgao', 'nome', name='uq_tipos_orgaos'),
    sa.UniqueConstraint('id_tipo_orgao', name=op.f('uq_camara_orgaos_tipos_id_tipo_orgao'))
    )
    op.create_table('erros_extract',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, cycle=False), nullable=False),
    sa.Column('lote_id', sa.Integer(), nullable=False),
    sa.Column('task', sa.String(length=50), nullable=False),
    sa.Column('data_hora', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('mensagem', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('baixado', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('data_hora_baixado', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lote_baixado', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lote_id'], ['lote.id'], name=op.f('fk_erros_extract_lote_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_erros_extract')),
    sa.UniqueConstraint('url', name=op.f('uq_erros_extract_url'))
    )
    op.create_table('log_linhas',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, cycle=False), nullable=False),
    sa.Column('id_lote', sa.Integer(), nullable=False),
    sa.Column('tabela', sa.Text(), nullable=False),
    sa.Column('inseridos', sa.Integer(), nullable=False),
    sa.Column('atualizados', sa.Integer(), nullable=False),
    sa.Column('ignorados', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_lote'], ['lote.id'], name=op.f('fk_log_linhas_id_lote')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_log_linhas'))
    )
    op.create_table('logs',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, cycle=False), nullable=False),
    sa.Column('lote_id', sa.Integer(), nullable=False),
    sa.Column('data_hora', sa.DateTime(timezone=True), nullable=True),
    sa.Column('level', sa.String(length=24), nullable=False),
    sa.Column('flow_run_name', sa.String(length=256), nullable=False),
    sa.Column('task_run_name', sa.String(length=256), nullable=True),
    sa.Column('mensagem', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['lote_id'], ['lote.id'], name=op.f('fk_logs_lote_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_logs'))
    )
    op.create_table('camara_blocos',
    sa.Column('id_bloco', sa.Integer(), nullable=False),
    sa.Column('nome', sa.Text(), nullable=False),
    sa.Column('id_legislatura', sa.Integer(), nullable=False),
    sa.Column('federacao', sa.Boolean(), nullable=False),
    sa.Column('id_lote', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, cycle=False), nullable=False),
    sa.ForeignKeyConstraint(['id_legislatura'], ['camara_legislatura.id_legislatura'], name=op.f('fk_camara_blocos_id_legislatura')),
    sa.ForeignKeyConstraint(['id_lote'], ['lote.id'], name=op.f('fk_camara_blocos_id_lote')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_camara_blocos')),
    sa.UniqueConstraint('id_bloco', name=op.f('uq_camara_blocos_id_bloco'))
    )
    op.create_table('camara_orgaos',
    sa.Column('id_orgao', sa.Integer(), nullable=False),
    sa.Column('sigla', sa.Text(), nullable=False),
    sa.Column('nome', sa.Text(), nullable=False),
    sa.Column('apelido', sa.Text(), nullable=False),
    sa.Column('id_tipo_orgao', sa.Integer(), nullable=False),
    sa.Column('nome_publicacao', sa.Text(), nullable=True),
    sa.Column('nome_resumido', sa.Text(), nullable=True),
    sa.Column('id_lote', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, cycle=False), nullable=False),
    sa.ForeignKeyConstraint(['id_lote'], ['lote.id'], name=op.f('fk_camara_orgaos_id_lote')),
    sa.ForeignKeyConstraint(['id_tipo_orgao'], ['camara_orgaos_tipos.id_tipo_orgao'], name=op.f('fk_camara_orgaos_id_tipo_orgao')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_camara_orgaos')),
    sa.UniqueConstraint('id_orgao', name=op.f('uq_camara_orgaos_id_orgao'))
    )
    op.create_table('camara_partidos',
    sa.Column('id_partido', sa.Integer(), nullable=False),
    sa.Column('sigla', sa.String(length=15), nullable=False),
    sa.Column('nome', sa.Text(), nullable=False),
    sa.Column('status_data', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id_legislatura', sa.Integer(), nullable=False),
    sa.Column('situacao', sa.Text(), nullable=True),
    sa.Column('total_posse', sa.Integer(), nullable=False),
    sa.Column('total_membros', sa.Integer(), nullable=False),
    sa.Column('id_lider', sa.Integer(), nullable=True),
    sa.Column('id_lote', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, cycle=False), nullable=False),
    sa.ForeignKeyConstraint(['id_legislatura'], ['camara_legislatura.id_legislatura'], name=op.f('fk_camara_partidos_id_legislatura')),
    sa.ForeignKeyConstraint(['id_lider'], ['camara_deputados.id_deputado'], name=op.f('fk_camara_partidos_id_lider'), use_alter=True),
    sa.ForeignKeyConstraint(['id_lote'], ['lote.id'], name=op.f('fk_camara_partidos_id_lote')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_camara_partidos')),
    sa.UniqueConstraint('id_partido', name=op.f('uq_camara_partidos_id_partido')),
    sa.UniqueConstraint('nome', name=op.f('uq_camara_partidos_nome')),
    sa.UniqueConstraint('sigla', name=op.f('uq_camara_partidos_sigla'))
    )
    op.create_table('camara_deputados',
    sa.Column('id_deputado', sa.Integer(), nullable=False),
    sa.Column('nome_civil', sa.Text(), nullable=False),
    sa.Column('nome', sa.Text(), nullable=False),
    sa.Column('id_partido', sa.Integer(), nullable=True),
    sa.Column('sigla_uf', sa.CHAR(length=2), nullable=False),
    sa.Column('id_legislatura', sa.Integer(), nullable=False),
    sa.Column('url_foto', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('data_ultimo_status', sa.Date(), nullable=False),
    sa.Column('nome_eleitoral', sa.Text(), nullable=False),
    sa.Column('gabinete_nome', sa.String(length=5), nullable=True),
    sa.Column('gabinete_predio', sa.String(length=2), nullable=True),
    sa.Column('gabinete_sala', sa.String(length=5), nullable=True),
    sa.Column('gabinete_andar', sa.String(length=2), nullable=True),
    sa.Column('gabinete_telefone', sa.CHAR(length=9), nullable=True),
    sa.Column('situacao', sa.Text(), nullable=False),
    sa.Column('condicao_eleitoral', sa.Text(), nullable=False),
    sa.Column('descricao_status', sa.Text(), nullable=True),
    sa.Column('cpf', sa.CHAR(length=11), nullable=False),
    sa.Column('sexo', sa.CHAR(length=1), nullable=False),
    sa.Column('data_nascimento', sa.Date(), nullable=False),
    sa.Column('data_falecimento', sa.Date(), nullable=True),
    sa.Column('uf_nascimento', sa.CHAR(length=2), nullable=False),
    sa.Column('municipio_nascimento', sa.Text(), nullable=False),
    sa.Column('escolaridade', sa.Text(), nullable=True),
    sa.Column('id_lote', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, cycle=False), nullable=False),
    sa.ForeignKeyConstraint(['id_legislatura'], ['camara_legislatura.id_legislatura'], name=op.f('fk_camara_deputados_id_legislatura')),
    sa.ForeignKeyConstraint(['id_lote'], ['lote.id'], name=op.f('fk_camara_deputados_id_lote')),
    sa.ForeignKeyConstraint(['id_partido'], ['camara_partidos.id_partido'], name=op.f('fk_camara_deputados_id_partido')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_camara_deputados')),
    sa.UniqueConstraint('id_deputado', name=op.f('uq_camara_deputados_id_deputado'))
    )
    op.create_table('camara_orgaos_detalhes',
    sa.Column('id_orgao', sa.Integer(), nullable=False),
    sa.Column('data_inicio', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_instalacao', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data_fim', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data_fim_original', sa.DateTime(timezone=True), nullable=True),
    sa.Column('url_website', sa.Text(), nullable=True),
    sa.Column('id_lote', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, cycle=False), nullable=False),
    sa.ForeignKeyConstraint(['id_lote'], ['lote.id'], name=op.f('fk_camara_orgaos_detalhes_id_lote')),
    sa.ForeignKeyConstraint(['id_orgao'], ['camara_orgaos.id_orgao'], name=op.f('fk_camara_orgaos_detalhes_id_orgao')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_camara_orgaos_detalhes')),
    sa.UniqueConstraint('id_orgao', name=op.f('uq_camara_orgaos_detalhes_id_orgao'))
    )
    op.create_table('camara_deputados_historico',
    sa.Column('id_deputado', sa.Integer(), nullable=False),
    sa.Column('nome', sa.Text(), nullable=False),
    sa.Column('sigla_partido', sa.String(length=15), nullable=False),
    sa.Column('sigla_uf', sa.CHAR(length=2), nullable=False),
    sa.Column('id_legislatura', sa.Integer(), nullable=False),
    sa.Column('data_hora', sa.DateTime(timezone=True), nullable=False),
    sa.Column('situacao', sa.Text(), nullable=True),
    sa.Column('condicao_eleitoral', sa.Text(), nullable=True),
    sa.Column('descricao_status', sa.Text(), nullable=True),
    sa.Column('nome_eleitoral', sa.Text(), nullable=True),
    sa.Column('hash', sa.CHAR(length=32), nullable=False),
    sa.Column('id_lote', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, cycle=False), nullable=False),
    sa.ForeignKeyConstraint(['id_deputado'], ['camara_deputados.id_deputado'], name=op.f('fk_camara_deputados_historico_id_deputado')),
    sa.ForeignKeyConstraint(['id_legislatura'], ['camara_legislatura.id_legislatura'], name=op.f('fk_camara_deputados_historico_id_legislatura')),
    sa.ForeignKeyConstraint(['id_lote'], ['lote.id'], name=op.f('fk_camara_deputados_historico_id_lote')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_camara_deputados_historico')),
    sa.UniqueConstraint('hash', name=op.f('uq_camara_deputados_historico_hash'))
    )
    op.create_table('camara_deputados_mandatos_externos',
    sa.Column('id_deputado', sa.Integer(), nullable=False),
    sa.Column('cargo', sa.Text(), nullable=False),
    sa.Column('sigla_uf', sa.CHAR(length=2), nullable=True),
    sa.Column('municipio', sa.Text(), nullable=True),
    sa.Column('ano_inicio', sa.Integer(), nullable=False),
    sa.Column('ano_fim', sa.Integer(), nullable=True),
    sa.Column('sigla_partido', sa.String(length=15), nullable=True),
    sa.Column('id_lote', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, cycle=False), nullable=False),
    sa.ForeignKeyConstraint(['id_deputado'], ['camara_deputados.id_deputado'], name=op.f('fk_camara_deputados_mandatos_externos_id_deputado')),
    sa.ForeignKeyConstraint(['id_lote'], ['lote.id'], name=op.f('fk_camara_deputados_mandatos_externos_id_lote')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_camara_deputados_mandatos_externos')),
    sa.UniqueConstraint('id_deputado', 'cargo', 'ano_inicio', name='uq_mandato_externo')
    )
    op.create_table('camara_deputados_ocupacoes',
    sa.Column('id_deputado', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.Text(), nullable=False),
    sa.Column('entidade', sa.Text(), nullable=True),
    sa.Column('entidade_uf', sa.CHAR(length=2), nullable=True),
    sa.Column('entidade_pais', sa.Text(), nullable=True),
    sa.Column('ano_inicio', sa.Integer(), nullable=False),
    sa.Column('ano_fim', sa.Integer(), nullable=True),
    sa.Column('id_lote', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, cycle=False), nullable=False),
    sa.ForeignKeyConstraint(['id_deputado'], ['camara_deputados.id_deputado'], name=op.f('fk_camara_deputados_ocupacoes_id_deputado')),
    sa.ForeignKeyConstraint(['id_lote'], ['lote.id'], name=op.f('fk_camara_deputados_ocupacoes_id_lote')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_camara_deputados_ocupacoes')),
    sa.UniqueConstraint('id_deputado', 'titulo', 'ano_inicio', name='uq_deputados_ocupacoes')
    )
    op.create_table('camara_deputados_profissoes',
    sa.Column('id_deputado', sa.Integer(), nullable=False),
    sa.Column('data_hora', sa.DateTime(timezone=True), nullable=True),
    sa.Column('titulo', sa.Text(), nullable=False),
    sa.Column('id_lote', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, cycle=False), nullable=False),
    sa.ForeignKeyConstraint(['id_deputado'], ['camara_deputados.id_deputado'], name=op.f('fk_camara_deputados_profissoes_id_deputado')),
    sa.ForeignKeyConstraint(['id_lote'], ['lote.id'], name=op.f('fk_camara_deputados_profissoes_id_lote')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_camara_deputados_profissoes')),
    sa.UniqueConstraint('id_deputado', 'titulo', name=op.f('uq_camara_deputados_profissoes_id_deputado'))
    )
    op.create_table('camara_deputados_redes_sociais',
    sa.Column('id_deputado', sa.Integer(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('id_lote', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, cycle=False), nullable=False),
    sa.ForeignKeyConstraint(['id_deputado'], ['camara_deputados.id_deputado'], name=op.f('fk_camara_deputados_redes_sociais_id_deputado')),
    sa.ForeignKeyConstraint(['id_lote'], ['lote.id'], name=op.f('fk_camara_deputados_redes_sociais_id_lote')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_camara_deputados_redes_sociais')),
    sa.UniqueConstraint('url', name=op.f('uq_camara_deputados_redes_sociais_url'))
    )
    op.create_table('camara_legislaturas_lideres',
    sa.Column('id_deputado', sa.Integer(), nullable=False),
    sa.Column('id_legislatura', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.Text(), nullable=False),
    sa.Column('bancada_tipo', sa.Text(), nullable=False),
    sa.Column('bancada_nome', sa.Text(), nullable=False),
    sa.Column('id_bancada', sa.Integer(), nullable=True),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=True),
    sa.Column('id_lote', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, cycle=False), nullable=False),
    sa.ForeignKeyConstraint(['id_deputado'], ['camara_deputados.id_deputado'], name=op.f('fk_camara_legislaturas_lideres_id_deputado')),
    sa.ForeignKeyConstraint(['id_legislatura'], ['camara_legislatura.id_legislatura'], name=op.f('fk_camara_legislaturas_lideres_id_legislatura')),
    sa.ForeignKeyConstraint(['id_lote'], ['lote.id'], name=op.f('fk_camara_legislaturas_lideres_id_lote')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_camara_legislaturas_lideres')),
    sa.UniqueConstraint('id_deputado', 'titulo', 'data_inicio', 'bancada_nome', name='uq_legislaturas_lideres')
    )
    op.create_table('camara_legislaturas_mesa',
    sa.Column('id_deputado', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.Text(), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=True),
    sa.Column('id_legislatura', sa.Integer(), nullable=False),
    sa.Column('id_lote', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, cycle=False), nullable=False),
    sa.ForeignKeyConstraint(['id_deputado'], ['camara_deputados.id_deputado'], name=op.f('fk_camara_legislaturas_mesa_id_deputado')),
    sa.ForeignKeyConstraint(['id_legislatura'], ['camara_legislatura.id_legislatura'], name=op.f('fk_camara_legislaturas_mesa_id_legislatura')),
    sa.ForeignKeyConstraint(['id_lote'], ['lote.id'], name=op.f('fk_camara_legislaturas_mesa_id_lote')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_camara_legislaturas_mesa')),
    sa.UniqueConstraint('id_deputado', 'titulo', 'data_inicio', name='uq_legislaturas_mesa')
    )
    op.create_table('camara_orgaos_membros',
    sa.Column('id_orgao', sa.Integer(), nullable=False),
    sa.Column('id_deputado', sa.Integer(), nullable=False),
    sa.Column('id_legislatura', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.Text(), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=True),
    sa.Column('id_lote', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, cycle=False), nullable=False),
    sa.ForeignKeyConstraint(['id_deputado'], ['camara_deputados.id_deputado'], name=op.f('fk_camara_orgaos_membros_id_deputado')),
    sa.ForeignKeyConstraint(['id_legislatura'], ['camara_legislatura.id_legislatura'], name=op.f('fk_camara_orgaos_membros_id_legislatura')),
    sa.ForeignKeyConstraint(['id_lote'], ['lote.id'], name=op.f('fk_camara_orgaos_membros_id_lote')),
    sa.ForeignKeyConstraint(['id_orgao'], ['camara_orgaos.id_orgao'], name=op.f('fk_camara_orgaos_membros_id_orgao')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_camara_orgaos_membros')),
    sa.UniqueConstraint('id_orgao', 'id_deputado', 'titulo', 'data_inicio', name='uq_orgaos_membros')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('camara_orgaos_membros')
    op.drop_table('camara_legislaturas_mesa')
    op.drop_table('camara_legislaturas_lideres')
    op.drop_table('camara_deputados_redes_sociais')
    op.drop_table('camara_deputados_profissoes')
    op.drop_table('camara_deputados_ocupacoes')
    op.drop_table('camara_deputados_mandatos_externos')
    op.drop_table('camara_deputados_historico')
    op.drop_table('camara_orgaos_detalhes')
    op.drop_table('camara_deputados')
    op.drop_table('camara_partidos')
    op.drop_table('camara_orgaos')
    op.drop_table('camara_blocos')
    op.drop_table('logs')
    op.drop_table('log_linhas')
    op.drop_table('erros_extract')
    op.drop_table('camara_orgaos_tipos')
    op.drop_table('camara_legislatura')
    op.drop_table('camara_blocos_partidos')
    op.drop_table('lote')
    # ### end Alembic commands ###
