"""fix legislaturas mesa e lideres

Revision ID: de9d848b7bb8
Revises: 74d3c3cd6d19
Create Date: 2026-03-05 16:26:53.352373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de9d848b7bb8'
down_revision: Union[str, Sequence[str], None] = '74d3c3cd6d19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_legislaturas_lideres', 'camara_legislaturas_lideres', ['id_deputado', 'titulo', 'data_inicio', 'bancada_nome'])
    op.add_column('camara_legislaturas_mesa', sa.Column('id_legislatura', sa.Integer(), nullable=False))
    op.create_unique_constraint('uq_legislaturas_mesa', 'camara_legislaturas_mesa', ['id_deputado', 'titulo', 'data_inicio'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_legislaturas_mesa', 'camara_legislaturas_mesa', type_='unique')
    op.drop_column('camara_legislaturas_mesa', 'id_legislatura')
    op.drop_constraint('uq_legislaturas_lideres', 'camara_legislaturas_lideres', type_='unique')
    # ### end Alembic commands ###
