"""empty message

Revision ID: dfc39418cd95
Revises: 9ac1f4e12bdd
Create Date: 2026-02-25 13:55:17.610483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfc39418cd95'
down_revision: Union[str, Sequence[str], None] = '9ac1f4e12bdd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('camara_deputados_historico',
    sa.Column('id_deputado', sa.Integer(), nullable=False),
    sa.Column('nome', sa.Text(), nullable=False),
    sa.Column('id_partido', sa.Integer(), nullable=False),
    sa.Column('sigla_uf', sa.CHAR(length=2), nullable=False),
    sa.Column('id_legislatura', sa.Integer(), nullable=False),
    sa.Column('data_hora', sa.DateTime(timezone=True), nullable=False),
    sa.Column('situacao', sa.Text(), nullable=True),
    sa.Column('condicao_eleitoral', sa.Text(), nullable=True),
    sa.Column('descricao_status', sa.Text(), nullable=True),
    sa.Column('nome_eleitoral', sa.Text(), nullable=False),
    sa.Column('id_lote', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, cycle=False), nullable=False),
    sa.ForeignKeyConstraint(['id_deputado'], ['camara_deputados.id_deputado'], name=op.f('fk_camara_deputados_historico_id_deputado')),
    sa.ForeignKeyConstraint(['id_lote'], ['lote.id'], name=op.f('fk_camara_deputados_historico_id_lote')),
    sa.ForeignKeyConstraint(['id_partido'], ['camara_partidos.id_partido'], name=op.f('fk_camara_deputados_historico_id_partido')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_camara_deputados_historico'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('camara_deputados_historico')
    # ### end Alembic commands ###
